# Generated by Django 4.2.5 on 2023-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='access_control',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='account_deactivation_deletion_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='alerts_and_reminders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='api_key_management',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='audit_logs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='contact_support',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='data_backup_and_restore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='data_export_import',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='error_logging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='faqs_and_tutorials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='feedback_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='font_size_and_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notification_preferences',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='privacy_settings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='security_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='surveys_and_user_research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='third_party_integrations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
