# Generated by Django 4.2.5 on 2023-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersettings_access_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='profile_information',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='two_factor_authentication',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='username_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
