# Generated by Django 4.2.5 on 2023-11-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usersettings_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('SMME', 'Small, Medium and Micro Enterprise'), ('Enterpize', 'Enterpizee')], default='Individual', max_length=30),
        ),
    ]
