# Generated by Django 4.2.5 on 2023-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermembership_renewal_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='username_email',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership_type',
            field=models.CharField(choices=[('Free Trail', 'Free Trail'), ('Individual', 'Individual'), ('SMME', 'Small, Medium and Micro Enterprise'), ('Enterpize', 'Enterpizee')], default='Free Trail', max_length=30),
        ),
    ]
