# Generated by Django 4.2.5 on 2023-11-21 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_usersettings_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signup_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
