# Generated by Django 4.2.5 on 2023-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='membership_type',
            field=models.CharField(choices=[('Free Trail', 'Free Trail'), ('Individual', 'Individual'), ('SMME', 'Small, Medium and Micro Enterprise'), ('Enterpise', 'Enterpise')], default='Free Trail', max_length=30),
        ),
    ]
