# Generated by Django 4.2.5 on 2023-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usermembership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='username_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
